services:
  postgres:
    image: postgres:16-alpine
    container_name: multi_tenant_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: giorgi
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multi_tenant_backend
    restart: always
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://neondb_owner:npg_jxruKcyYUN97@ep-green-cell-ay7i2bi3-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      JWT_SECRET: 6d1c8ff1f2505350cb05c50bed2fd155b93062d6589ae0cd09e68adfc9e66421
      JWT_REFRESH_SECRET: 18d9010a967ccbda5cb5670c3cc25cf3bdd5b29ed65a1a895a381d23a8182548
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
